### ISSUE TITLE
Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract` ?

### ISSUE THREAD

**Issue by max6186** [deepnight/gameBase#100]
I don't know why "@:enum" is the issue and I was think if delete the "@:" from every single one is a good idea or not?

[Log.txt](https://github.com/deepnight/gameBase/files/12429555/Log.txt)

**Comment by deepnight** [comment]
Yes,
```haxe
@:enum abstract Xyz 
```

is the same as 

```haxe
enum abstract Xyz
```

However, the warnings refer to various haxelibs, so you may need to create a proper PR for them on git to get all the warnings fixed for good.

**Comment by kLabz** [comment]
Alternatively, you can compile with `-w -WDeprecated` to disable those warnings

**Comment by max6186** [comment]
> 

I did get the haxelibs by compile "setup.hxml" from the root.
