### ISSUE TITLE
Console shortcut

### ISSUE THREAD

**Issue by putois-blagueur** [deepnight/gameBase#101]
Hey deepnight,

First of all, thank you for this template. My issue is more like a question, hopefully this is an appropriate channel ? Or maybe there is another, discord or something similar ?
Anyway, I'm trying to understand how the console works. In the comment in App.hxml it states that the console should open by pressing '²' but I don't have this key on my keyboard, so I wanted to change the binding, but I can't find it. The closest thing I could find is ctrl+shift+F which seems to open the debug flags window, is is the same thing ? From reading the code it seems the console should do more than juste offering those flags.

Thanks !

**Comment by dooderino** [comment]
In my experience, it was the '/' key that opened the console. Does that
work for you?

**Comment by putois-blagueur** [comment]
It does indeed, thank you.
Although I'm still confused on the way it works: I see no explicit binding to '/' in the code. Is that a heaps.io builtin ?

**Comment by deepnight** [comment]
It does open the console (somehow), because "/" is the first character for all console commands. It's implemented somewhere in the `h2d.Console` 🤷

**Comment by dooderino** [comment]
Yes, I see it in h2d/Console.hx on line 93ish.
