### ISSUE TITLE
Encounter "Failed to load library directx.hdll" Error When Running GameBase Project on wsl2

### ISSUE THREAD

**Issue by Andyyyy64** [deepnight/gameBase#108]
Hi,

I'm new to Haxe and the Heaps engine, and I'm attempting to build a simple RPG game for learning purposes. I decided to use the gameBase repository as a starting point. However, I'm encountering a recurring error when trying to run the game:
```
src/module.c(373) : FATAL ERROR : Failed to load library directx.hdll
```
I followed these steps based on the guidelines provided for the gameBase project:

1. Installed Haxe (I can compile .hx files and run them without issues).
2. Installed Heaps.
3. Executed the following commands as per the setup instructions:
    - haxe setup.hxml
    - haxe build.directx.hxml
    - hl bin/client.hl

Despite these efforts, the error persists. Here's an additional context that might be helpful:

![image](https://github.com/deepnight/gameBase/assets/105579829/263a7bbe-2594-4531-8b20-8ed2073cab9e)

```
haxelib list
ase: [2.0.3]
castle: [git]
deepnightLibs: 1.0.80 [git]
format: [3.7.0]
hashlink: git [dev:/home/andy/haxelib/hashlink/git/other/haxelib/]
heaps-aseprite: 0.1.2 [git]
heaps: 2.0.0 [git]
hldx: 1.14.0 git [dev:/home/andy/haxelib/hldx/git/libs/directx]
hlopenal: [1.5.0]
hlsdl: 1.14.0 git [dev:/home/andy/haxelib/hlsdl/git/libs/sdl]
hscript: 2.5.0 [git]
hxcpp-debug-server: [dev:/home/andy/.vscode-server/extensions/vshaxe.hxcpp-debugger-1.2.4/hxcpp-debug-server]
ldtk-haxe-api: 1.0.0 [git]
redistHelper: [0.7.3]
```
```
 hl
HL/JIT 1.14.0 (c)2015-2023 Haxe Foundation
  Usage : hl [--debug <port>] [--debug-wait] <file>
```

I'm using WSL for my development environment. Could this be related to the issue? Any suggestions on how to resolve this error would be greatly appreciated.

Thank you for your assistance.

**Comment by dooderino** [comment]
I'm only guessing here, but I believe you will want to use
build.opengl.hxml rather than directx.

**Comment by Andyyyy64** [comment]
thank you for the response!!
I try it but it shows another error...
![image](https://github.com/deepnight/gameBase/assets/105579829/cf3f9825-af4d-4c19-8d7a-1689cf1fc0e9)
all build options shows some kinda error and i have no clue.
