### ISSUE TITLE
data.cdb doesnt load in catleDB

### ISSUE THREAD

**Issue by daimahou** [deepnight/gameBase#112]
CastleDB doesnt recognize a value type. When loaded, CatleDB output the following error msg:  "Unkow type 17"

**Comment by kLabz** [comment]
You might want to use castledb editor from Hide instead: https://github.com/HeapsIO/hide (can be started with castledb UI only with `HIDE_START_CDB=1` env)

Standalone castledb editor is outdated

**Comment by deepnight** [comment]
You can use my fork of HIDE directly:
https://github.com/deepnight/hide

I keep it up in sync with the official version from times to times and ensure everything works with it.

**Comment by deepnight** [comment]
I added a release to github which contains a recently built HIDE. Follow the instructions to run it:

https://github.com/deepnight/hide/releases/tag/stable-2024-09-24
