### ISSUE TITLE
Use of 3d?

### ISSUE THREAD

**Issue by JerryGreen** [deepnight/gameBase#12]
I want something close to Starcraft 2, i.e. 3d game in 2d space. They seem to use the same approach to coordinate system, which you covered in [A simple and generic 2D engine, part 1 - Coordinates system](https://deepnight.net/tutorial/a-simple-platformer-engine-part-1-basics/#2-0) (great article btw), also similar to both Northgard and Darksburg.

It seems it fits very well for such usage, even though this gameBase doesn't contain s3d at all (and I haven't found such in advancedBase either). Can you give some insight on what changes your template might need, like Game.hx, Entity.hx, and maybe other classes, to implement this RTS-like experience?

**Comment by deepnight** [comment]
Hi!
I don't use 3D myself, but yes, it should be easy to use GameBase for a 3D based project. All you'll need is to:

 - replace the Entity.spr stuff with a 3D model
 - add some Z related fields (like `dz` for the Z velocity etc.)

The logic should stay the same 🤔
