### ISSUE TITLE
No player?

### ISSUE THREAD

**Issue by botolo78** [deepnight/gameBase#13]
Hi, I noticed you updated the advanced branch with an ldtk map and I wanted to check how it works.
I've no issues compiling with haxe and running with hashlink, but I noticed there's no player entity in the demo.

**Comment by deepnight** [comment]
Hi!
Yes, there's no player entity by default, as not all game required one (or some need multiples). You can easily make one for you by extending `Entity` class, and adding controller checks in the `update()` loop :)
