### ISSUE TITLE
Compiling Error: Class<dn.heaps.Scaler> has no field bestFit (Suggestions: bestFit_i, bestFit_f)

### ISSUE THREAD

**Issue by harshetmaruff** [deepnight/gameBase#26]
harshet@harshet-desktop:~/Desktop/Game_Program_Learning/Heaps.io/For_Web/demo$ haxe js.hxml
src/Const.hx:16: characters 27-34 : Class<dn.heaps.Scaler> has no field bestFit (Suggestions: bestFit_i, bestFit_f)
harshet@harshet-desktop:~/Desktop/Game_Program_Learning/Heaps.io/For_Web/demo$

**Comment by harshetmaruff** [comment]
I have an issue in compiling please help

**Comment by deepnight** [comment]
Hi,
you should either update gameBase from git, or replace `bestFit(...)`with `bestFit_i(...)`
