### ISSUE TITLE
how to run hxml task?

### ISSUE THREAD

**Issue by Lightnet** [deepnight/gameBase#3]
I am not sure which ext. that run hxml. It ignore the build.

**Comment by ConstNW** [comment]
You need to install [Haxe](https://deepnight.net/tutorial/using-my-gamebase-to-create-a-heaps-game/#2-1)

**Comment by Lightnet** [comment]
I know I install it haxe. I using vscode and install ext haxe pack. But I can't run vscode type "hxml" it get ignore.

**Comment by ConstNW** [comment]
press `F5` in vscode

**Comment by Lightnet** [comment]
I did that but error.

```
Error: The hxml task detection didn't contribute a task for the following configuration:
{
    "label": "JS debug",
    "type": "hxml",
    "file": "js.debug.hxml",
    "presentation": {
        "reveal": "never",
        "panel": "dedicated",
        "clear": true
    },
    "problemMatcher": [
        "$haxe"
    ]
}
The task will be ignored.
```

**Comment by ConstNW** [comment]
be sure that u have installed [haxe extension](https://marketplace.visualstudio.com/items?itemName=nadako.vshaxe)

**Comment by Lightnet** [comment]
I tried few times looking around. It seem something change but not sure. It say it The task will be ignored.

https://community.haxe.org/t/hashlink-vscode-debugger-problem/2291/4
https://community.haxe.org/t/tasks-json-compiler-arguments/1758/2

But I did try the other task and works.

```
{
            "label": "Build HL",
            "command":"haxe",
            "args": ["build.hxml", "-debug"],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": [
                "$haxe-absolute",
                "$haxe",
                "$haxe-error",
                "$haxe-trace"
            ]
        }
```

**Comment by deepnight** [comment]
To make sure it's not a Haxe related bug, please try running the following command from a Command Line, inside your project folder:

```haxe hl.debug.hxml```

If you don't get any error, and that creates a ``client.hl``  file in the ``bin`` directory, that's good.
Then it means the problem is related to your VScode setup. Please make sure you have Haxe extensions installed and working.
