### ISSUE TITLE
How to remove the green square in the game base sample

### ISSUE THREAD

**Issue by harshetmaruff** [deepnight/gameBase#32]
Hey deepnight I followed your tutorial which was in deepnight.net . Which is crating the hero but I see a small green square. How to remove it

**Comment by enumm** [comment]
That's a placeholder texture. You need to set entity image.

**Comment by harshetmaruff** [comment]
> That's a placeholder texture. You need to set entity image.

How to do that ???

I actually did that like this

g = h2d.Graphics(spr);
g.beginTileFill(0,0,0.5,0.5,heroimg);
g.draw(0,0,heroimg.width,heroimg.height);

**Comment by harshetmaruff** [comment]
Yes found it 
spr.setTexture(heroimg)
