### ISSUE TITLE
Camera rotation

### ISSUE THREAD

**Issue by edwinsyarief** [deepnight/gameBase#33]
Hi @deepnight ,

Is there any example camera rotation?

Thank you

**Comment by deepnight** [comment]
Sorry, I don't have any example for that 🤔 IMHO, a good approach would be to replace x/y coordinates of Camera with a Matrix, and use matrix transformations (rotation + translation) to get final coordinates.

**Comment by edwinsyarief** [comment]
Okay, thanks
