### ISSUE TITLE
Exception has occurred. Access Violation When trying to run hl.dx.hxml

### ISSUE THREAD

**Issue by josajunior81** [deepnight/gameBase#35]
Thread.hx line 98 threadsMutex.acquire();
Exception has occurred.
Access Violation

**Comment by harshetmaruff** [comment]
which operating system are you using...
I dont seem to get the errors on my computer....,
Also which haxe and heaps version are you using

**Comment by josajunior81** [comment]
Hi,

Windows 10 20H2
Haxe 4.2.0
HL 1.11.0
Heaps: 1.8.0

**Comment by harshetmaruff** [comment]
update your heaps version and try it again

**Comment by deepnight** [comment]
Hi!
You should use the git version of Heaps:

`haxelib git heaps https://github.com/deepnight/heaps.git`

**Comment by josajunior81** [comment]
Thanks guys! I've updated but didn't work. Either way now I know that the problem is with my heaps install. I'll try to solve with your tips!

**Comment by josajunior81** [comment]
Hi,

I think the problem was with the Haxe version (https://github.com/HaxeFoundation/hashlink/issues/446). Either way I've compiled the hashlink myself and it's working perfectly. 

Thankyou guys! Thanks deepnight your work and content is awesome!
