### ISSUE TITLE
How to Have Collision (GameBase)

### ISSUE THREAD

**Issue by harshetmaruff** [deepnight/gameBase#37]
Hi deepnight how to have collision in heaps / game, like the hero in platformer having collision in the ground

**Comment by harshetmaruff** [comment]
pls anyone any idea

**Comment by deepnight** [comment]
Hi :) It's explained in depth here, and that's pretty much how my gamebase works:
https://deepnight.net/tutorial/a-simple-platformer-engine-part-1-basics/

There's no predefined collision system or shapes, you have to do the collision logic by yourself.
