### ISSUE TITLE
How to use LangParser?

### ISSUE THREAD

**Issue by saeldion** [deepnight/gameBase#5]
I'm trying to figure out how to use the included LangParser. Am I correct that it's purpose is to create `.mo` files from the `*.po` files?

It's has been compiled but when i run `hl bin/langParse.hl` I get the output:

```
Building sourceTexts file...
[GetText] Parsing source code...
[GetText] Parsing CDBs...
  -> res/data.cdb
[GetText] Saving POT file (res/lang/sourceTexts.pot)...
[GetText] done.
Done.
```
However, no `en.mo` file is created. All that is created is a `sourceTexts.pot` which does not contain the correct translation.

If I change the translation for "Game is ready" to "TEST" in `en.po`:
```
#: src/Game.hx:19
msgid "Game is ready."
msgstr "TEST"
```

The generated `sourceTexts.pot` looks unchanged:
```
#: src/Game.hx:32
msgid "Game is ready."
msgstr ""
```

I also noticed this section in `LangParser.hx` has an error in vscode:
```
var data = GetText.doParseGlobal({
	codePath: "src",
	codeIgnore: null,
	cdbFiles: cdbs,
	cdbSpecialId: [],
	potFile: "res/lang/"+name+".pot",
});
```
```
Class<dn.data.GetText> has no field doParseGlobal
```

There is no information about the LangParser in the documentation (tutorial on deepnight or the README)

**Comment by deepnight** [comment]
I wrote a very short documentation about that here: https://github.com/deepnight/gameBase/wiki/Localization 

The idea is:

1. You use Lang.t._("my string that needs translation") in your code,
2. You run LangParser to extract these strings into a POT file (that's a catalog file)
3. You run POEdit and create a new "translation", by setting the source language (English here), and the target language (say French for example)
4. You save that as a PO file. Doing that will also create the MO file which is basically a binary version of your PO.

**Comment by deepnight** [comment]
I wrote an updated guide here: https://deepnight.net/tutorial/part-4-localize-texts-using-po-files/
