### ISSUE TITLE
Failed to load library directx.hdll

### ISSUE THREAD

**Issue by alberteddu** [deepnight/gameBase#53]
Hey — first of all, thanks a lot for sharing this! I was looking forward to try this out (coming from Unity), but I'm unable to start the game (right after cloning).

> $ haxe hl.dx.hxml
> $ hl bin/client.hl
> src/module.c(360) : FATAL ERROR : Failed to load library directx.hdll

I'm on MacOS. Writing an issue here because I have no idea how to debug and googling didn't help. Let me know if I can share anything else about my environment that can help find the problem.

**Comment by deepnight** [comment]
Hi!
On macos, you should build either a HL+SDL version or a JS version. The `hl.dx.hxml` stands for DirectX:
```
haxe hl.sdl.hxml
```
or
```
haxe js.hxml
```

**Comment by alberteddu** [comment]
Thanks a lot!
