### ISSUE TITLE
Strange slowdowns while using a wireless Xbox controller?

### ISSUE THREAD

**Issue by deepnight** [deepnight/gameBase#6]

**Comment by deepnight** [comment]
"Fixed", controller was actually broken 😑

**Comment by kLabz** [comment]
Did you push the changes? Or did you fix this long ago?

**Comment by deepnight** [comment]
Oh, my bad: actually it solved by itself at some point. Not sure if it was Haxe/Heaps related or something. Do you still have the issue?

**Comment by kLabz** [comment]
I don't know, was just wondering if I was missing some fixes related to controller; but it seems mostly fine (though my game isn't demanding at all so I could miss performance issues)

**Comment by deepnight** [comment]
Ok! Keep me updated if this happens again 🤔

**Comment by phelioz** [comment]
I think I actually have a similar problem right now. Get stutter/slowdowns when I connect my Xbox One Wireless controller. But I don't get it on my Dualshock 4 controller.

Get this problem both with your deepnightLibs Controller and by using Pad directly with Pad.wait.
Open a issue on Heaps repo about this: https://github.com/HeapsIO/heaps/issues/1042

If remember how you solved it I would be really grateful if you share it :)
