### ISSUE TITLE
Need update dn.heaps.Controller

### ISSUE THREAD

**Issue by kondr1** [deepnight/gameBase#65]
I follow the tutorial on your site and notice you updated dn.heaps.Controller. This class was move to namespace dn.heaps.inputs, so this project does not assemble now =(

**Comment by AshtomGVA** [comment]
Hello, sorry in advance if I misunderstood but I replaced _dn.heaps.Controller_ with **dn.heaps.input.Controller** but I get the following error and I'm not sure what type to define:
**Not enough type parameters for dn.heaps.input.Controller**

I tried several options, including 
```haxe
var ca : dn.heaps.input.Controller<en.MyGameActions>;
```

But then I get errors down the line in the **new** function on
```haxe
ca = Main.ME.controller.createAccess("hero"); // creates an instance of controller
```

_Error: dn.legacy.ControllerAccess should be dn.heaps.input.Controller<en.MyGameActions>_

And now I'm quite confused.

**Comment by deepnight** [comment]
Hi,
Sorry, the Controller class was completely reworked recently.

You can simply rename any occurrence of `dn.heaps.Controller` to `dn.legacy.Controller` to use the old version (the one explained in the tutorial). 

I'll try to re-write these docs as soon as possible, but right now I'm a bit overwhelmed 😅

**Comment by AshtomGVA** [comment]
Thanks for the help and for taking the time.
