### ISSUE TITLE
This is blatantly unfair! Why can't we transfer our subscription

### ISSUE THREAD

**Issue by humanoidcorn447** [deepnight/gameBase#72]
There has to be a way to transfer a subscription to another device! We can't just buy the same subscription we already have! We demand change!

**Comment by deepnight** [comment]
Hi,
Excuse me, but what are you talking about?

**Comment by humanoidcorn447** [comment]
I’m talking about why we can’t have the same subscription from the previous device! I just got a galaxy tab s7+ just for the app called the gamebase. and now it’s telling me to buy the same subscription again, even though I already bought it…TWICE! Is there anyway to fix this!?

**Comment by deepnight** [comment]
You're at the wrong place unfortunately. This github page is totally unrelated to your Gamebase app :)
Check here: https://gamebase.app/
