### ISSUE TITLE
Error during first start. (master branch)

### ISSUE THREAD

**Issue by nosferatu500** [deepnight/gameBase#73]
Hey! Thanks for your work and lessons. I have no experience with Haxe and I'm just trying to follow the instructions from your website and during the next step `haxe build.js.hxml` I am getting an error:
```
/usr/local/lib/haxe/lib/heaps/git/hxd/fmt/hmd/Library.hx:729: characters 85-104 : Type not found : hrt.prefab.Resource
/usr/local/lib/haxe/lib/heaps/git/hxd/res/Any.hx:21: lines 21-71 : ... Defined in this class
```

PS: After `haxe setup.hxml` nothing was changed.
PPS: MacOS 12.3

**Comment by jdsmith2816** [comment]
I'm in the exact same situation currently.

**Comment by jdsmith2816** [comment]
Looks like heaps master branch is currently broken.  Fork it, make a branch with head of `60e66bc92fe58da374e4a03a933ac8ab8c7c6367` then run 

````shell
haxelib remove heaps
haxelib git heaps http://github.com/nosferatu500/heaps your-branch-name
```
The type not found error should go away after this.  Remember to swap back to the main heaps repo once a fix is pushed.

**Comment by nosferatu500** [comment]
I thought about it too. Thanks, I'll do that.
